### ISSUE TITLE
Koinos Cap'n Proto

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-proto#1]
As a Koinos developer, I would like libraries generated in each language representing core Koinos types.

- [ ] Express all fundamental Koinos types in Cap'n Proto files (#2)
- [ ] Attempt integration with https://github.com/nickolasrossi/podgen (#3)
- [x] Create necessary language specific repositories for generated types
- [x] Utilize CI to generate types in target languages (C++, Golang) (#4)
   - [x] C++ generated files should be in a CMake library format when uploaded to the repo
   - [x] Golang generated files should be in a Golang module format when uploaded to the repo

---

* `system_call_id` and `thunk_id` will collapse in to a single enum `system_call_id` which will be a normal enumeration (no specialized default values)
* `contract_id` and `account_type` will now follow a hexadecimal representation system wide (`json` and when shown to the user)
* `db_put_object` and `db_get_object` key and space will go from uint256 to `Data` over the wire
* `resource_limit` will be converted from `uint128` to `uint64`
