### ISSUE TITLE
Canonical serialization

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-proto#21]
As a user of the Koinos blockchain, I would like a method to canonicalize serialize transactions for signing.

* [x] Write and document canonical serialization specification and add to `docs.koinos.io` (koinos/koinos-io-website#66)
* [x] Implement said specification in `koinos-proto-cpp` (koinos/koinos-proto-cpp#1)
* [x] Implement said specification in `koinos-proto-golang` (koinos/koinos-proto-golang#1)
* [x] Implement said specification in `koinos-proto-embedded-cpp` (koinos/koinos-proto-embedded-cpp#1)
